name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.7', '3.5', '3.6' ]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Reinstall pip using constrained version
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install tox
        run: pip install tox

      - name: Run tox tests and linters
        run: tox -e py
